name: #name of the exporter
url: #url including http/https of the CSV-based API to export, parts with <varName> are taken from additionalVariables: http://<varName> -> http://sample 
requireAuthentication: #true/false
authenticationMethod: #one of: bearer-token
pollingIntervalHours: #int
additionalVariables:
  # Variables that contain only uppercase letters are taken from environment variables
  varName: sample
